<a href="https://colab.research.google.com/github/edithavalos/react-crud-app/blob/master/Ejercicios_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ClassicModels
El esquema es para Classic Models, un minorista de modelos a escala de coches clásicos. La base de datos contiene datos comerciales típicos, como clientes, pedidos, artículos de línea de pedido, productos, etc.

Fuente original: www.mysqltutorial.org

![classicmodels[1].svg]()

### Ejercicios de SQL utilizando el esquema de base de datos ClassicModels:

1. Obtén todos los registros de la tabla `customers`.

2. Muestra todos los productos de la tabla `products` cuyo precio de compra (`buyPrice`) sea mayor a 50.

3. Lista los empleados que trabajan en la oficina con código `officeCode` igual a 1.

4. Encuentra todos los clientes cuyo nombre (`customerName`) comienza con la letra 'A'.

5. Cuenta cuántos pedidos (`orders`) ha realizado el cliente con número de cliente (`customerNumber`) 103.

6. Calcula el total de pagos realizados por el cliente con número de cliente 112.

7. Encuentra el producto con el precio de compra más alto en la tabla `products`.

8. Muestra los 5 productos más vendidos según la cantidad pedida en `orderdetails`.

9. Lista todas las oficinas y el número de empleados que trabajan en cada una.

10. Encuentra el número total de clientes atendidos por cada representante de ventas (`salesRepEmployeeNumber`).

11. Muestra todos los productos y su línea de producto (`productLine`), ordenados alfabéticamente por línea de producto.

12. Calcula el importe total de todas las órdenes sumando el resultado de `quantityOrdered` por `priceEach` en `orderdetails`.

13. Encuentra todos los pedidos que han sido enviados después del 1 de enero de 2004.

14. Lista los clientes y sus pagos totales, ordenados de mayor a menor.

15. Muestra los empleados que no reportan a ningún gerente (es decir, cuyo campo `reportsTo` es NULL).

16. Encuentra los clientes que no han realizado ningún pedido.

17. Muestra los productos que nunca han sido vendidos en ningún pedido.

18. Calcula el precio de compra promedio de todos los productos.

19. Lista los clientes y el número de pedidos que han realizado.

20. Encuentra el total de ventas por año.

21. Muestra los detalles de las órdenes combinados con la información del producto para cada artículo.

22. Encuentra los empleados que trabajan en oficinas ubicadas en los Estados Unidos.

23. Lista los clientes junto con el nombre de su representante de ventas.

24. Calcula el total de pagos recibidos en cada ciudad.

25. Muestra los productos que tienen menos de 100 unidades en stock (`quantityInStock`).

26. Encuentra los clientes que han realizado pedidos con un monto total superior a $10,000.

27. Lista los empleados y el número de clientes que atienden.

28. Calcula el importe total de los pedidos que están en proceso (estado 'In Process').

29. Encuentra los productos que han sido pedidos más de 100 veces en total.

30. Muestra las líneas de productos y el número de productos que pertenecen a cada línea.

Estos ejercicios abarcan diversas consultas y operaciones que pueden realizarse en la base de datos ClassicModels, incluyendo selección, agregación, ordenamiento, uniones y subconsultas.

In [1]:
%matplotlib inline
import matplotlib
import seaborn as sns
matplotlib.rcParams['savefig.dpi'] = 144

In [2]:
%%capture
!apt-get install postgresql postgresql-contrib
!pip install ipython-sql psycopg2-binary pymysql sqlalchemy

In [3]:
!service postgresql start
!sudo -u postgres createdb classicmodels
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

 * Starting PostgreSQL 14 database server
   ...done.
ALTER ROLE


In [4]:
%load_ext sql
%sql postgresql://postgres:postgres@localhost/classicmodels

In [5]:
import pandas as pd
from sqlalchemy import create_engine, inspect

# Parámetros de conexión para MariaDB
mariadb_usuario = 'guest'
mariadb_contraseña = 'relational'
mariadb_host = 'db.relational-data.org'  # o la dirección de tu host
mariadb_puerto = 3306  # Puerto por defecto para MariaDB/MySQL
mariadb_base_datos = 'classicmodels'

# Parámetros de conexión para PostgreSQL
postgres_usuario = 'postgres'
postgres_contraseña = 'postgres'
postgres_host = 'localhost'  # o la dirección de tu host
postgres_puerto = 5432  # Puerto por defecto para PostgreSQL
postgres_base_datos = 'classicmodels'

# Crear el motor de conexión para MariaDB
mariadb_engine = create_engine(
    f'mysql+pymysql://{mariadb_usuario}:{mariadb_contraseña}@{mariadb_host}:{mariadb_puerto}/{mariadb_base_datos}'
)

# Crear el motor de conexión para PostgreSQL
postgres_engine = create_engine(
    f'postgresql+psycopg2://{postgres_usuario}:{postgres_contraseña}@{postgres_host}:{postgres_puerto}/{postgres_base_datos}'
)

# Obtener la lista de tablas de MariaDB
inspector = inspect(mariadb_engine)
tablas = inspector.get_table_names()

# Iterar sobre las tablas y copiarlas a PostgreSQL
for nombre_tabla in tablas:
    print(f"Procesando la tabla {nombre_tabla}")
    df = pd.read_sql_table(nombre_tabla, mariadb_engine)
    df.to_sql(nombre_tabla, postgres_engine, index=False, if_exists='replace')
    print(f"Tabla {nombre_tabla} copiada exitosamente.")


Procesando la tabla customers
Tabla customers copiada exitosamente.
Procesando la tabla employees
Tabla employees copiada exitosamente.
Procesando la tabla offices
Tabla offices copiada exitosamente.
Procesando la tabla orderdetails
Tabla orderdetails copiada exitosamente.
Procesando la tabla orders
Tabla orders copiada exitosamente.
Procesando la tabla payments
Tabla payments copiada exitosamente.
Procesando la tabla productlines
Tabla productlines copiada exitosamente.
Procesando la tabla products
Tabla products copiada exitosamente.


In [6]:
%%sql

select *
from customers
limit 10;

 * postgresql://postgres:***@localhost/classicmodels
10 rows affected.


[(103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370.0, 21000.0),
 (112, 'Signal Gift Stores', 'King', 'Jean', '7025551838', '8489 Strong St.', None, 'Las Vegas', 'NV', '83030', 'USA', 1166.0, 71800.0),
 (114, 'Australian Collectors, Co.', 'Ferguson', 'Peter', '03 9520 4555', '636 St Kilda Road', 'Level 3', 'Melbourne', 'Victoria', '3004', 'Australia', 1611.0, 117300.0),
 (119, 'La Rochelle Gifts', 'Labrune', 'Janine ', '40.67.8555', '67, rue des Cinquante Otages', None, 'Nantes', None, '44000', 'France', 1370.0, 118200.0),
 (121, 'Baane Mini Imports', 'Bergulfsen', 'Jonas ', '07-98 9555', 'Erling Skakkes gate 78', None, 'Stavern', None, '4110', 'Norway', 1504.0, 81700.0),
 (124, 'Mini Gifts Distributors Ltd.', 'Nelson', 'Susan', '4155551450', '5677 Strong St.', None, 'San Rafael', 'CA', '97562', 'USA', 1165.0, 210500.0),
 (125, 'Havel & Zbyszek Co', 'Piestrzeniewicz', 'Zbyszek ', '(26) 642-7555', 'ul. Filtrowa 68', None, 'Warszawa', None, '01-012', 'Poland', None, 0.0),
 (128, 'Blauer See Auto, Co.', 'Keitel', 'Roland', '+49 69 66 90 2555', 'Lyonerstr. 34', None, 'Frankfurt', None, '60528', 'Germany', 1504.0, 59700.0),
 (129, 'Mini Wheels Co.', 'Murphy', 'Julie', '6505555787', '5557 North Pendale Street', None, 'San Francisco', 'CA', '94217', 'USA', 1165.0, 64600.0),
 (131, 'Land of Toys Inc.', 'Lee', 'Kwai', '2125557818', '897 Long Airport Avenue', None, 'NYC', 'NY', '10022', 'USA', 1323.0, 114900.0)]

In [7]:
%%sql

select *
from employees
limit 10;

 * postgresql://postgres:***@localhost/classicmodels
10 rows affected.


[(1002, 'Murphy', 'Diane', 'x5800', 'dmurphy@classicmodelcars.com', '1', None, 'President'),
 (1056, 'Patterson', 'Mary', 'x4611', 'mpatterso@classicmodelcars.com', '1', 1002.0, 'VP Sales'),
 (1076, 'Firrelli', 'Jeff', 'x9273', 'jfirrelli@classicmodelcars.com', '1', 1002.0, 'VP Marketing'),
 (1088, 'Patterson', 'William', 'x4871', 'wpatterson@classicmodelcars.com', '6', 1056.0, 'Sales Manager (APAC)'),
 (1102, 'Bondur', 'Gerard', 'x5408', 'gbondur@classicmodelcars.com', '4', 1056.0, 'Sale Manager (EMEA)'),
 (1143, 'Bow', 'Anthony', 'x5428', 'abow@classicmodelcars.com', '1', 1056.0, 'Sales Manager (NA)'),
 (1165, 'Jennings', 'Leslie', 'x3291', 'ljennings@classicmodelcars.com', '1', 1143.0, 'Sales Rep'),
 (1166, 'Thompson', 'Leslie', 'x4065', 'lthompson@classicmodelcars.com', '1', 1143.0, 'Sales Rep'),
 (1188, 'Firrelli', 'Julie', 'x2173', 'jfirrelli@classicmodelcars.com', '2', 1143.0, 'Sales Rep'),
 (1216, 'Patterson', 'Steve', 'x4334', 'spatterson@classicmodelcars.com', '2', 1143.0, 'Sales Rep')]

In [8]:
%%sql

select *
from offices
limit 10;

 * postgresql://postgres:***@localhost/classicmodels
7 rows affected.


[('1', 'San Francisco', '+1 650 219 4782', '100 Market Street', 'Suite 300', 'CA', 'USA', '94080', 'NA'),
 ('2', 'Boston', '+1 215 837 0825', '1550 Court Place', 'Suite 102', 'MA', 'USA', '02107', 'NA'),
 ('3', 'NYC', '+1 212 555 3000', '523 East 53rd Street', 'apt. 5A', 'NY', 'USA', '10022', 'NA'),
 ('4', 'Paris', '+33 14 723 4404', "43 Rue Jouffroy D'abbans", None, None, 'France', '75017', 'EMEA'),
 ('5', 'Tokyo', '+81 33 224 5000', '4-1 Kioicho', None, 'Chiyoda-Ku', 'Japan', '102-8578', 'Japan'),
 ('6', 'Sydney', '+61 2 9264 2451', '5-11 Wentworth Avenue', 'Floor #2', None, 'Australia', 'NSW 2010', 'APAC'),
 ('7', 'London', '+44 20 7877 2041', '25 Old Broad Street', 'Level 7', None, 'UK', 'EC2N 1HN', 'EMEA')]

In [9]:
%%sql

select *
from orderdetails
limit 10;

 * postgresql://postgres:***@localhost/classicmodels
10 rows affected.


[(10100, 'S18_1749', 30, 136.0, 3),
 (10100, 'S18_2248', 50, 55.09, 2),
 (10100, 'S18_4409', 22, 75.46, 4),
 (10100, 'S24_3969', 49, 35.29, 1),
 (10101, 'S18_2325', 25, 108.06, 4),
 (10101, 'S18_2795', 26, 167.06, 1),
 (10101, 'S24_1937', 45, 32.53, 3),
 (10101, 'S24_2022', 46, 44.35, 2),
 (10102, 'S18_1342', 39, 95.55, 2),
 (10102, 'S18_1367', 41, 43.13, 1)]

In [10]:
%%sql

select *
from orders
limit 10;

 * postgresql://postgres:***@localhost/classicmodels
10 rows affected.


[(10100, datetime.datetime(2003, 1, 6, 0, 0), datetime.datetime(2003, 1, 13, 0, 0), datetime.datetime(2003, 1, 10, 0, 0), 'Shipped', None, 363),
 (10101, datetime.datetime(2003, 1, 9, 0, 0), datetime.datetime(2003, 1, 18, 0, 0), datetime.datetime(2003, 1, 11, 0, 0), 'Shipped', 'Check on availability.', 128),
 (10102, datetime.datetime(2003, 1, 10, 0, 0), datetime.datetime(2003, 1, 18, 0, 0), datetime.datetime(2003, 1, 14, 0, 0), 'Shipped', None, 181),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), datetime.datetime(2003, 2, 7, 0, 0), datetime.datetime(2003, 2, 2, 0, 0), 'Shipped', None, 121),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), datetime.datetime(2003, 2, 9, 0, 0), datetime.datetime(2003, 2, 1, 0, 0), 'Shipped', None, 141),
 (10105, datetime.datetime(2003, 2, 11, 0, 0), datetime.datetime(2003, 2, 21, 0, 0), datetime.datetime(2003, 2, 12, 0, 0), 'Shipped', None, 145),
 (10106, datetime.datetime(2003, 2, 17, 0, 0), datetime.datetime(2003, 2, 24, 0, 0), datetime.datetime(2003, 2, 21, 0, 0), 'Shipped', None, 278),
 (10107, datetime.datetime(2003, 2, 24, 0, 0), datetime.datetime(2003, 3, 3, 0, 0), datetime.datetime(2003, 2, 26, 0, 0), 'Shipped', 'Difficult to negotiate with customer. We need more marketing materials', 131),
 (10108, datetime.datetime(2003, 3, 3, 0, 0), datetime.datetime(2003, 3, 12, 0, 0), datetime.datetime(2003, 3, 8, 0, 0), 'Shipped', None, 385),
 (10109, datetime.datetime(2003, 3, 10, 0, 0), datetime.datetime(2003, 3, 19, 0, 0), datetime.datetime(2003, 3, 11, 0, 0), 'Shipped', 'Customer requested that FedEx Ground is used for this shipping', 486)]

In [11]:
%%sql

select *
from payments
limit 10;

 * postgresql://postgres:***@localhost/classicmodels
10 rows affected.


[(103, 'HQ336336', datetime.datetime(2004, 10, 19, 0, 0), 6066.78),
 (103, 'JM555205', datetime.datetime(2003, 6, 5, 0, 0), 14571.44),
 (103, 'OM314933', datetime.datetime(2004, 12, 18, 0, 0), 1676.14),
 (112, 'BO864823', datetime.datetime(2004, 12, 17, 0, 0), 14191.12),
 (112, 'HQ55022', datetime.datetime(2003, 6, 6, 0, 0), 32641.98),
 (112, 'ND748579', datetime.datetime(2004, 8, 20, 0, 0), 33347.88),
 (114, 'GG31455', datetime.datetime(2003, 5, 20, 0, 0), 45864.03),
 (114, 'MA765515', datetime.datetime(2004, 12, 15, 0, 0), 82261.22),
 (114, 'NP603840', datetime.datetime(2003, 5, 31, 0, 0), 7565.08),
 (114, 'NR27552', datetime.datetime(2004, 3, 10, 0, 0), 44894.74)]

In [12]:
%%sql

select *
from productlines
limit 10;

 * postgresql://postgres:***@localhost/classicmodels
7 rows affected.


[('Classic Cars', 'Attention car enthusiasts: Make your wildest car ownership dreams come true. Whether you are looking for classic muscle cars, dream sports cars or mo ... (437 characters truncated) ... cles. All models include a certificate of authenticity from their manufacturers and come fully assembled and ready for display in the home or office.', None, None),
 ('Motorcycles', 'Our motorcycles are state of the art replicas of classic as well as contemporary motorcycle legends such as Harley Davidson, Ducati and Vespa. Models ... (297 characters truncated) ...  out-of-production vehicles. All models come fully assembled and ready for display in the home or office. Most include a certificate of authenticity.', None, None),
 ('Planes', 'Unique, diecast airplane and helicopter replicas suitable for collections, as well as home, office or classroom decorations. Models contain stunning  ... (55 characters truncated) ... jet engines and propellers, retractable wheels, and so on. Most come fully assembled and with a certificate of authenticity from their manufacturers.', None, None),
 ('Ships', 'The perfect holiday or anniversary gift for executives, clients, friends, and family. These handcrafted model ships are unique, stunning works of art ... (12 characters truncated) ... e treasured for generations! They come fully assembled and ready for display in the home or office. We guarantee the highest quality, and best value.', None, None),
 ('Trains', "Model trains are a rewarding hobby for enthusiasts of all ages. Whether you're looking for collectible wooden trains, electric streetcars or locomoti ... (73 characters truncated) ... egory. The interactive aspect of trains makes toy trains perfect for young children. The wooden train sets are ideal for children under the age of 5.", None, None),
 ('Trucks and Buses', 'The Truck and Bus models are realistic replicas of buses and specialized trucks produced from the early 1920s to present. The models range in size fr ... (124 characters truncated) ... n, diecast and plastic. All models include a certificate of authenticity from their manufacturers and are a perfect ornament for the home and office.', None, None),
 ('Vintage Cars', 'Our Vintage Car models realistically portray automobiles produced from the early 1900s through the 1940s. Materials used include Bakelite, diecast, p ... (202 characters truncated) ... icas. All models include a certificate of authenticity from their manufacturers and come fully assembled and ready for display in the home or office.', None, None)]

In [13]:
%%sql

select *
from products
limit 10;

 * postgresql://postgres:***@localhost/classicmodels
10 rows affected.


[('S10_1678', '1969 Harley Davidson Ultimate Chopper', 'Motorcycles', '1:10', 'Min Lin Diecast', 'This replica features working kickstand, front suspension, gear-shift lever, footbrake lever, drive chain, wheels and steering. All parts are particularly delicate due to their precise scale and require special care and attention.', 7933, 48.81, 95.7),
 ('S10_1949', '1952 Alpine Renault 1300', 'Classic Cars', '1:10', 'Classic Metal Creations', 'Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 7305, 98.58, 214.3),
 ('S10_2016', '1996 Moto Guzzi 1100i', 'Motorcycles', '1:10', 'Highway 66 Mini Classics', 'Official Moto Guzzi logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, two leathe ... (93 characters truncated) ... paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand, diecast metal with plastic parts and baked enamel finish.', 6625, 68.99, 118.94),
 ('S10_4698', '2003 Harley-Davidson Eagle Drag Bike', 'Motorcycles', '1:10', 'Red Start Diecast', 'Model features, official Harley Davidson logos and insignias, detachable rear wheelie bar, heavy diecast metal with resin parts, authentic multi-colo ... (199 characters truncated) ... t replica, baked enamel finish, 1:10 scale model, removable fender, seat and tank cover piece for displaying the superior detail of the v-twin engine', 5582, 91.02, 193.66),
 ('S10_4757', '1972 Alfa Romeo GTA', 'Classic Cars', '1:10', 'Motor City Art Classics', 'Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 3252, 85.68, 136.0),
 ('S10_4962', '1962 LanciaA Delta 16V', 'Classic Cars', '1:10', 'Second Gear Diecast', 'Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 6791, 103.42, 147.74),
 ('S12_1099', '1968 Ford Mustang', 'Classic Cars', '1:12', 'Autoart Studio Design', 'Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color dark green.', 68, 95.34, 194.57),
 ('S12_1108', '2001 Ferrari Enzo', 'Classic Cars', '1:12', 'Second Gear Diecast', 'Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 3619, 95.59, 207.8),
 ('S12_1666', '1958 Setra Bus', 'Trucks and Buses', '1:12', 'Welly Diecast Productions', 'Model features 30 windows, skylights & glare resistant glass, working steering system, original logos', 1579, 77.9, 136.67),
 ('S12_2823', '2002 Suzuki XREO', 'Motorcycles', '1:12', 'Unimax Art Galleries', 'Official logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, two leather seats, lu ... (82 characters truncated) ... paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand, diecast metal with plastic parts and baked enamel finish.', 9997, 66.27, 150.62)]

# **EJERCICIOS**

1. Obtén todos los registros de la tabla customers.

In [15]:
%%sql
 SELECT * FROM customers

 * postgresql://postgres:***@localhost/classicmodels
122 rows affected.


[(103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370.0, 21000.0),
 (112, 'Signal Gift Stores', 'King', 'Jean', '7025551838', '8489 Strong St.', None, 'Las Vegas', 'NV', '83030', 'USA', 1166.0, 71800.0),
 (114, 'Australian Collectors, Co.', 'Ferguson', 'Peter', '03 9520 4555', '636 St Kilda Road', 'Level 3', 'Melbourne', 'Victoria', '3004', 'Australia', 1611.0, 117300.0),
 (119, 'La Rochelle Gifts', 'Labrune', 'Janine ', '40.67.8555', '67, rue des Cinquante Otages', None, 'Nantes', None, '44000', 'France', 1370.0, 118200.0),
 (121, 'Baane Mini Imports', 'Bergulfsen', 'Jonas ', '07-98 9555', 'Erling Skakkes gate 78', None, 'Stavern', None, '4110', 'Norway', 1504.0, 81700.0),
 (124, 'Mini Gifts Distributors Ltd.', 'Nelson', 'Susan', '4155551450', '5677 Strong St.', None, 'San Rafael', 'CA', '97562', 'USA', 1165.0, 210500.0),
 (125, 'Havel & Zbyszek Co', 'Piestrzeniewicz', 'Zbyszek ', '(26) 642-7555', 'ul. Filtrowa 68', None, 'Warszawa', None, '01-012', 'Poland', None, 0.0),
 (128, 'Blauer See Auto, Co.', 'Keitel', 'Roland', '+49 69 66 90 2555', 'Lyonerstr. 34', None, 'Frankfurt', None, '60528', 'Germany', 1504.0, 59700.0),
 (129, 'Mini Wheels Co.', 'Murphy', 'Julie', '6505555787', '5557 North Pendale Street', None, 'San Francisco', 'CA', '94217', 'USA', 1165.0, 64600.0),
 (131, 'Land of Toys Inc.', 'Lee', 'Kwai', '2125557818', '897 Long Airport Avenue', None, 'NYC', 'NY', '10022', 'USA', 1323.0, 114900.0),
 (141, 'Euro+ Shopping Channel', 'Freyre', 'Diego ', '(91) 555 94 44', 'C/ Moralzarzal, 86', None, 'Madrid', None, '28034', 'Spain', 1370.0, 227600.0),
 (144, 'Volvo Model Replicas, Co', 'Berglund', 'Christina ', '0921-12 3555', 'Berguvsvägen  8', None, 'Luleå', None, 'S-958 22', 'Sweden', 1504.0, 53100.0),
 (145, 'Danish Wholesale Imports', 'Petersen', 'Jytte ', '31 12 3555', 'Vinbæltet 34', None, 'Kobenhavn', None, '1734', 'Denmark', 1401.0, 83400.0),
 (146, 'Saveley & Henriot, Co.', 'Saveley', 'Mary ', '78.32.5555', '2, rue du Commerce', None, 'Lyon', None, '69004', 'France', 1337.0, 123900.0),
 (148, 'Dragon Souveniers, Ltd.', 'Natividad', 'Eric', '+65 221 7555', 'Bronz Sok.', 'Bronz Apt. 3/6 Tesvikiye', 'Singapore', None, '079903', 'Singapore', 1621.0, 103800.0),
 (151, 'Muscle Machine Inc', 'Young', 'Jeff', '2125557413', '4092 Furth Circle', 'Suite 400', 'NYC', 'NY', '10022', 'USA', 1286.0, 138500.0),
 (157, 'Diecast Classics Inc.', 'Leong', 'Kelvin', '2155551555', '7586 Pompton St.', None, 'Allentown', 'PA', '70267', 'USA', 1216.0, 100600.0),
 (161, 'Technics Stores Inc.', 'Hashimoto', 'Juri', '6505556809', '9408 Furth Circle', None, 'Burlingame', 'CA', '94217', 'USA', 1165.0, 84600.0),
 (166, 'Handji Gifts& Co', 'Victorino', 'Wendy', '+65 224 1555', '106 Linden Road Sandown', '2nd Floor', 'Singapore', None, '069045', 'Singapore', 1612.0, 97900.0),
 (167, 'Herkku Gifts', 'Oeztan', 'Veysel', '+47 2267 3215', 'Brehmen St. 121', 'PR 334 Sentrum', 'Bergen', None, 'N 5804', 'Norway  ', 1504.0, 96800.0),
 (168, 'American Souvenirs Inc', 'Franco', 'Keith', '2035557845', '149 Spinnaker Dr.', 'Suite 101', 'New Haven', 'CT', '97823', 'USA', 1286.0, 0.0),
 (169, 'Porto Imports Co.', 'de Castro', 'Isabel ', '(1) 356-5555', 'Estrada da saúde n. 58', None, 'Lisboa', None, '1756', 'Portugal', None, 0.0),
 (171, 'Daedalus Designs Imports', 'Rancé', 'Martine ', '20.16.1555', '184, chaussée de Tournai', None, 'Lille', None, '59000', 'France', 1370.0, 82900.0),
 (172, "La Corne D'abondance, Co.", 'Bertrand', 'Marie', '(1) 42.34.2555', '265, boulevard Charonne', None, 'Paris', None, '75012', 'France', 1337.0, 84300.0),
 (173, 'Cambridge Collectables Co.', 'Tseng', 'Jerry', '6175555555', '4658 Baden Av.', None, 'Cambridge', 'MA', '51247', 'USA', 1188.0, 43400.0),
 (175, 'Gift Depot Inc.', 'King', 'Julie', '2035552570', '25593 South Bay Ln.', None, 'Bridgewater', 'CT', '97562', 'USA', 1323.0, 84300.0),
 (177, 'Osaka Souveniers Co.', 'Kentary', 'Mory', '+81 06 6342 5555

2. Muestra todos los productos de la tabla products cuyo precio de compra (buyPrice) sea mayor a 50.

In [18]:
%%sql
SELECT * FROM products WHERE "buyPrice" > 50

 * postgresql://postgres:***@localhost/classicmodels
62 rows affected.


[('S10_1949', '1952 Alpine Renault 1300', 'Classic Cars', '1:10', 'Classic Metal Creations', 'Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 7305, 98.58, 214.3),
 ('S10_2016', '1996 Moto Guzzi 1100i', 'Motorcycles', '1:10', 'Highway 66 Mini Classics', 'Official Moto Guzzi logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, two leathe ... (93 characters truncated) ... paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand, diecast metal with plastic parts and baked enamel finish.', 6625, 68.99, 118.94),
 ('S10_4698', '2003 Harley-Davidson Eagle Drag Bike', 'Motorcycles', '1:10', 'Red Start Diecast', 'Model features, official Harley Davidson logos and insignias, detachable rear wheelie bar, heavy diecast metal with resin parts, authentic multi-colo ... (199 characters truncated) ... t replica, baked enamel finish, 1:10 scale model, removable fender, seat and tank cover piece for displaying the superior detail of the v-twin engine', 5582, 91.02, 193.66),
 ('S10_4757', '1972 Alfa Romeo GTA', 'Classic Cars', '1:10', 'Motor City Art Classics', 'Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 3252, 85.68, 136.0),
 ('S10_4962', '1962 LanciaA Delta 16V', 'Classic Cars', '1:10', 'Second Gear Diecast', 'Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 6791, 103.42, 147.74),
 ('S12_1099', '1968 Ford Mustang', 'Classic Cars', '1:12', 'Autoart Studio Design', 'Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color dark green.', 68, 95.34, 194.57),
 ('S12_1108', '2001 Ferrari Enzo', 'Classic Cars', '1:12', 'Second Gear Diecast', 'Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 3619, 95.59, 207.8),
 ('S12_1666', '1958 Setra Bus', 'Trucks and Buses', '1:12', 'Welly Diecast Productions', 'Model features 30 windows, skylights & glare resistant glass, working steering system, original logos', 1579, 77.9, 136.67),
 ('S12_2823', '2002 Suzuki XREO', 'Motorcycles', '1:12', 'Unimax Art Galleries', 'Official logos and insignias, saddle bags located on side of motorcycle, detailed engine, working steering, working suspension, two leather seats, lu ... (82 characters truncated) ... paint with chrome accents, superior die-cast detail , rotating wheels , working kick stand, diecast metal with plastic parts and baked enamel finish.', 9997, 66.27, 150.62),
 ('S12_3148', '1969 Corvair Monza', 'Classic Cars', '1:18', 'Welly Diecast Productions', '1:18 scale die-cast about 10" long doors open, hood opens, trunk opens and wheels roll', 6906, 89.14, 151.08),
 ('S12_3380', '1968 Dodge Charger', 'Classic Cars', '1:12', 'Welly Diecast Productions', '1:12 scale model of a 1968 Dodge Charger. Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color black', 9123, 75.16, 117.44),
 ('S12_3891', '1969 Ford Falcon', 'Classic Cars', '1:12', 'Second Gear Diecast', 'Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 1049, 83.05, 173.02),
 ('S12_4473', '1957 Chevy Pickup', 'Trucks and Buses', '1:12', 'Exoto Designs', '1:12 scale die-cast about 20" long Hood opens, Rubber wheels', 6125, 55.7, 118.5),
 ('S12_4675', '1969 Dodge Charger', 'Classic Cars', '1:12', 'Welly Diecast Productions', 'Detailed model of the 1969 Dodge Charger. This model includes finely detailed interior and exterior features. Painted in red and whi

3. Lista los empleados que trabajan en la oficina con código officeCode igual a 1.

In [19]:
%%sql
SELECT * FROM employees WHERE "officeCode" = '1'

 * postgresql://postgres:***@localhost/classicmodels
6 rows affected.


[(1002, 'Murphy', 'Diane', 'x5800', 'dmurphy@classicmodelcars.com', '1', None, 'President'),
 (1056, 'Patterson', 'Mary', 'x4611', 'mpatterso@classicmodelcars.com', '1', 1002.0, 'VP Sales'),
 (1076, 'Firrelli', 'Jeff', 'x9273', 'jfirrelli@classicmodelcars.com', '1', 1002.0, 'VP Marketing'),
 (1143, 'Bow', 'Anthony', 'x5428', 'abow@classicmodelcars.com', '1', 1056.0, 'Sales Manager (NA)'),
 (1165, 'Jennings', 'Leslie', 'x3291', 'ljennings@classicmodelcars.com', '1', 1143.0, 'Sales Rep'),
 (1166, 'Thompson', 'Leslie', 'x4065', 'lthompson@classicmodelcars.com', '1', 1143.0, 'Sales Rep')]

4. Encuentra todos los clientes cuyo nombre (customerName) comienza con la letra 'A'.

In [20]:
%%sql
SELECT * FROM customers WHERE "customerName" LIKE 'A%'

 * postgresql://postgres:***@localhost/classicmodels
16 rows affected.


[(103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370.0, 21000.0),
 (114, 'Australian Collectors, Co.', 'Ferguson', 'Peter', '03 9520 4555', '636 St Kilda Road', 'Level 3', 'Melbourne', 'Victoria', '3004', 'Australia', 1611.0, 117300.0),
 (168, 'American Souvenirs Inc', 'Franco', 'Keith', '2035557845', '149 Spinnaker Dr.', 'Suite 101', 'New Haven', 'CT', '97823', 'USA', 1286.0, 0.0),
 (187, 'AV Stores, Co.', 'Ashworth', 'Rachel', '(171) 555-1555', 'Fauntleroy Circus', None, 'Manchester', None, 'EC2 5NT', 'UK', 1501.0, 136800.0),
 (198, 'Auto-Moto Classics Inc.', 'Taylor', 'Leslie', '6175558428', '16780 Pompton St.', None, 'Brickhaven', 'MA', '58339', 'USA', 1216.0, 23000.0),
 (206, 'Asian Shopping Network, Co', 'Walker', 'Brydey', '+612 9411 1555', 'Suntec Tower Three', '8 Temasek', 'Singapore', None, '038988', 'Singapore', None, 0.0),
 (237, 'ANG Resellers', 'Camino', 'Alejandra ', '(91) 745 6555', 'Gran Vía, 1', None, 'Madrid', None, '28001', 'Spain', None, 0.0),
 (242, 'Alpha Cognac', 'Roulet', 'Annette ', '61.77.6555', '1 rue Alsace-Lorraine', None, 'Toulouse', None, '31000', 'France', 1370.0, 61100.0),
 (249, 'Amica Models & Co.', 'Accorti', 'Paolo ', '011-4988555', 'Via Monte Bianco 34', None, 'Torino', None, '10100', 'Italy', 1401.0, 113000.0),
 (256, 'Auto Associés & Cie.', 'Tonini', 'Daniel ', '30.59.8555', "67, avenue de l'Europe", None, 'Versailles', None, '78000', 'France', 1370.0, 77900.0),
 (276, "Anna's Decorations, Ltd", "O'Hara", 'Anna', '02 9936 8555', '201 Miller Street', 'Level 15', 'North Sydney', 'NSW', '2060', 'Australia', 1611.0, 107800.0),
 (333, 'Australian Gift Network, Co', 'Calaghan', 'Ben', '61-7-3844-6555', '31 Duncan St. West End', None, 'South Brisbane', 'Queensland', '4101', 'Australia', 1611.0, 51600.0),
 (348, 'Asian Treasures, Inc.', 'McKenna', 'Patricia ', '2967 555', '8 Johnstown Road', None, 'Cork', 'Co. Cork', None, 'Ireland', None, 0.0),
 (406, 'Auto Canal+ Petit', 'Perrier', 'Dominique', '(1) 47.55.6555', '25, rue Lauriston', None, 'Paris', None, '75016', 'France', 1337.0, 95000.0),
 (465, 'Anton Designs, Ltd.', 'Anton', 'Carmen', '+34 913 728555', 'c/ Gobelas, 19-1 Urb. La Florida', None, 'Madrid', None, '28023', 'Spain', None, 0.0),
 (471, 'Australian Collectables, Ltd', 'Clenahan', 'Sean', '61-9-3844-6555', '7 Allen Street', None, 'Glen Waverly', 'Victoria', '3150', 'Australia', 1611.0, 60300.0)]

5. Cuenta cuántos pedidos (orders) ha realizado el cliente con número de cliente (customerNumber) 103.


In [21]:
%%sql
SELECT COUNT(*) FROM orders WHERE "customerNumber" = 103

 * postgresql://postgres:***@localhost/classicmodels
1 rows affected.


[(3,)]

6. Calcula el total de pagos realizados por el cliente con número de cliente 112.

In [22]:
%%sql
SELECT SUM("amount") FROM payments WHERE "customerNumber" = 112

 * postgresql://postgres:***@localhost/classicmodels
1 rows affected.


[(80180.98,)]

7. Encuentra el producto con el precio de compra más alto en la tabla products.

In [23]:
%%sql
SELECT * FROM products ORDER BY "buyPrice" DESC LIMIT 1

 * postgresql://postgres:***@localhost/classicmodels
1 rows affected.


[('S10_4962', '1962 LanciaA Delta 16V', 'Classic Cars', '1:10', 'Second Gear Diecast', 'Features include: Turnable front wheels; steering function; detailed interior; detailed engine; opening hood; opening trunk; opening doors; and detailed chassis.', 6791, 103.42, 147.74)]

8. Muestra los 5 productos más vendidos según la cantidad pedida en orderdetails.

In [24]:
%%sql
SELECT * FROM products a
INNER JOIN orderdetails b on b."productCode" = a."productCode"
ORDER BY b."quantityOrdered" DESC LIMIT 5

 * postgresql://postgres:***@localhost/classicmodels
5 rows affected.


[('S12_4675', '1969 Dodge Charger', 'Classic Cars', '1:12', 'Welly Diecast Productions', 'Detailed model of the 1969 Dodge Charger. This model includes finely detailed interior and exterior features. Painted in red and white.', 7323, 58.73, 115.16, 10405, 'S12_4675', 97, 115.16, 5),
 ('S18_3278', '1969 Dodge Super Bee', 'Classic Cars', '1:18', 'Min Lin Diecast', 'This replica features opening doors, superb detail and craftsmanship, working steering system, opening forward compartment, opening rear trunk with removable spare, 4 wheel independent spring suspension as well as factory baked enamel finish.', 1917, 49.05, 80.41, 10404, 'S18_3278', 90, 67.54, 6),
 ('S700_2466', 'America West Airlines B757-200', 'Planes', '1:700', 'Motor City Art Classics', 'Official logos and insignias. Working steering system. Rotating jet engines', 9653, 68.8, 99.72, 10401, 'S700_2466', 85, 98.72, 10),
 ('S700_3167', 'F/A 18 Hornet 1/72', 'Planes', '1:72', 'Motor City Art Classics', '10" Wingspan with retractable landing gears.Comes with pilot', 551, 54.4, 80.0, 10401, 'S700_3167', 77, 73.6, 9),
 ('S12_3990', '1970 Plymouth Hemi Cuda', 'Classic Cars', '1:12', 'Studio M Art Models', 'Very detailed 1970 Plymouth Cuda model in 1:12 scale. The Cuda is generally accepted as one of the fastest original muscle cars from the 1970s. This model is a reproduction of one of the orginal 652 cars built in 1970. Red color.', 5663, 31.92, 79.8, 10404, 'S12_3990', 77, 67.03, 4)]

9. Lista todas las oficinas y el número de empleados que trabajan en cada una.

In [25]:
%%sql
SELECT a."officeCode", COUNT(b."employeeNumber") as CantidadEmpleados FROM offices a
INNER JOIN employees b on b."officeCode" = a."officeCode"
GROUP BY a."officeCode"
ORDER BY CantidadEmpleados DESC

 * postgresql://postgres:***@localhost/classicmodels
7 rows affected.


[('1', 6), ('4', 5), ('6', 4), ('5', 2), ('3', 2), ('7', 2), ('2', 2)]

10. Encuentra el número total de clientes atendidos por cada representante de ventas (salesRepEmployeeNumber).

In [26]:
%%sql
SELECT "salesRepEmployeeNumber", COUNT(*) FROM customers
GROUP BY "salesRepEmployeeNumber"

 * postgresql://postgres:***@localhost/classicmodels
16 rows affected.


[(None, 22),
 (1504.0, 9),
 (1323.0, 8),
 (1166.0, 6),
 (1702.0, 6),
 (1165.0, 6),
 (1501.0, 8),
 (1611.0, 5),
 (1286.0, 7),
 (1612.0, 5),
 (1401.0, 10),
 (1370.0, 7),
 (1188.0, 6),
 (1621.0, 5),
 (1337.0, 6),
 (1216.0, 6)]

11. Muestra todos los productos y su línea de producto (productLine), ordenados alfabéticamente por línea de producto.

In [41]:
%%sql
SELECT p."productName", p."productLine"	 FROM products p
ORDER BY p."productLine", p."productName";

 * postgresql://postgres:***@localhost/classicmodels
110 rows affected.


[('1948 Porsche 356-A Roadster', 'Classic Cars'),
 ('1948 Porsche Type 356 Roadster', 'Classic Cars'),
 ('1949 Jaguar XK 120', 'Classic Cars'),
 ('1952 Alpine Renault 1300', 'Classic Cars'),
 ('1952 Citroen-15CV', 'Classic Cars'),
 ('1956 Porsche 356A Coupe', 'Classic Cars'),
 ('1957 Corvette Convertible', 'Classic Cars'),
 ('1957 Ford Thunderbird', 'Classic Cars'),
 ('1958 Chevy Corvette Limited Edition', 'Classic Cars'),
 ('1961 Chevrolet Impala', 'Classic Cars'),
 ('1962 LanciaA Delta 16V', 'Classic Cars'),
 ('1965 Aston Martin DB5', 'Classic Cars'),
 ('1966 Shelby Cobra 427 S/C', 'Classic Cars'),
 ('1968 Dodge Charger', 'Classic Cars'),
 ('1968 Ford Mustang', 'Classic Cars'),
 ('1969 Chevrolet Camaro Z28', 'Classic Cars'),
 ('1969 Corvair Monza', 'Classic Cars'),
 ('1969 Dodge Charger', 'Classic Cars'),
 ('1969 Dodge Super Bee', 'Classic Cars'),
 ('1969 Ford Falcon', 'Classic Cars'),
 ('1970 Chevy Chevelle SS 454', 'Classic Cars'),
 ('1970 Dodge Coronet', 'Classic Cars'),
 ('1970 Plymouth Hemi Cuda', 'Classic Cars'),
 ('1970 Triumph Spitfire', 'Classic Cars'),
 ('1971 Alpine Renault 1600s', 'Classic Cars'),
 ('1972 Alfa Romeo GTA', 'Classic Cars'),
 ('1976 Ford Gran Torino', 'Classic Cars'),
 ('1982 Camaro Z28', 'Classic Cars'),
 ('1982 Lamborghini Diablo', 'Classic Cars'),
 ('1985 Toyota Supra', 'Classic Cars'),
 ('1992 Ferrari 360 Spider red', 'Classic Cars'),
 ('1992 Porsche Cayenne Turbo Silver', 'Classic Cars'),
 ('1993 Mazda RX-7', 'Classic Cars'),
 ('1995 Honda Civic', 'Classic Cars'),
 ('1998 Chrysler Plymouth Prowler', 'Classic Cars'),
 ('1999 Indy 500 Monte Carlo SS', 'Classic Cars'),
 ('2001 Ferrari Enzo', 'Classic Cars'),
 ('2002 Chevy Corvette', 'Classic Cars'),
 ('1936 Harley Davidson El Knucklehead', 'Motorcycles'),
 ('1957 Vespa GS150', 'Motorcycles'),
 ('1960 BSA Gold Star DBD34', 'Motorcycles'),
 ('1969 Harley Davidson Ultimate Chopper', 'Motorcycles'),
 ('1974 Ducati 350 Mk3 Desmo', 'Motorcycles'),
 ('1982 Ducati 900 Monster', 'Motorcycles'),
 ('1982 Ducati 996 R', 'Motorcycles'),
 ('1996 Moto Guzzi 1100i', 'Motorcycles'),
 ('1997 BMW F650 ST', 'Motorcycles'),
 ('1997 BMW R 1100 S', 'Motorcycles'),
 ('2002 Suzuki XREO', 'Motorcycles'),
 ('2002 Yamaha YZR M1', 'Motorcycles'),
 ('2003 Harley-Davidson Eagle Drag Bike', 'Motorcycles'),
 ('1900s Vintage Bi-Plane', 'Planes'),
 ('1900s Vintage Tri-Plane', 'Planes'),
 ('1928 British Royal Navy Airplane', 'Planes'),
 ('1980s Black Hawk Helicopter', 'Planes'),
 ('American Airlines: B767-300', 'Planes'),
 ('American Airlines: MD-11S', 'Planes'),
 ('America West Airlines B757-200', 'Planes'),
 ('ATA: B757-300', 'Planes'),
 ('Boeing X-32A JSF', 'Planes'),
 ('Corsair F4U ( Bird Cage)', 'Planes'),
 ('F/A 18 Hornet 1/72', 'Planes'),
 ('P-51-D Mustang', 'Planes'),
 ('18th century schooner', 'Ships'),
 ('1999 Yamaha Speed Boat', 'Ships'),
 ('HMS Bounty', 'Ships'),
 ('Pont Yacht', 'Ships'),
 ('The Mayflower', 'Ships'),
 ('The Queen Mary', 'Ships'),
 ('The Schooner Bluenose', 'Ships'),
 ('The Titanic', 'Ships'),
 ('The USS Constitution Ship', 'Ships'),
 ("1950's Chicago Surface Lines Streetcar", 'Trains'),
 ('1962 City of Detroit Streetcar', 'Trains'),
 ('Collectable Wooden Train', 'Trains'),
 ('1926 Ford Fire Engine', 'Trucks and Buses'),
 ('1940 Ford Pickup Truck', 'Trucks and Buses'),
 ('1940s Ford truck', 'Trucks and Buses'),
 ('1954 Greyhound Scenicruiser', 'Trucks and Buses'),
 ('1957 Chevy Pickup', 'Trucks and Buses'),
 ('1958 Setra Bus', 'Trucks and Buses'),
 ('1962 Volkswagen Microbus', 'Trucks and Buses'),
 ('1964 Mercedes Tour Bus', 'Trucks and Buses'),
 ('1980’s GM Manhattan Express', 'Trucks and Buses'),
 ('1996 Peterbilt 379 Stake Bed with Outrigger', 'Trucks and Buses'),
 ('Diamond T620 Semi-Skirted Tanker', 'Trucks and Buses'),
 ('18th Century Vintage Horse Carriage', 'Vintage Cars'),
 ('1903 Ford Model A', 'Vintage Cars'),
 ('1904 Buick Runabout', 'Vintage Cars'),
 ('1911 Ford Town Car', 'Vintage Cars'),
 ('1912 Ford Model T Delivery Wagon', 'Vintage Cars')

12. Calcula el importe total de todas las órdenes sumando el resultado de quantityOrdered por priceEach en orderdetails.

In [42]:
%%sql
SELECT SUM(o."quantityOrdered" * o."priceEach") AS total_importe
FROM orderdetails o;

 * postgresql://postgres:***@localhost/classicmodels
1 rows affected.


[(9604190.609999985,)]

13. Encuentra todos los pedidos que han sido enviados después del 1 de enero de 2004.

In [43]:
%%sql
SELECT * FROM orders o
   WHERE o."shippedDate" > '2004-01-01';

 * postgresql://postgres:***@localhost/classicmodels
202 rows affected.


[(10266, datetime.datetime(2004, 7, 6, 0, 0), datetime.datetime(2004, 7, 14, 0, 0), datetime.datetime(2004, 7, 10, 0, 0), 'Shipped', None, 386),
 (10267, datetime.datetime(2004, 7, 7, 0, 0), datetime.datetime(2004, 7, 17, 0, 0), datetime.datetime(2004, 7, 9, 0, 0), 'Shipped', None, 151),
 (10208, datetime.datetime(2004, 1, 2, 0, 0), datetime.datetime(2004, 1, 11, 0, 0), datetime.datetime(2004, 1, 4, 0, 0), 'Shipped', None, 146),
 (10209, datetime.datetime(2004, 1, 9, 0, 0), datetime.datetime(2004, 1, 15, 0, 0), datetime.datetime(2004, 1, 12, 0, 0), 'Shipped', None, 347),
 (10210, datetime.datetime(2004, 1, 12, 0, 0), datetime.datetime(2004, 1, 22, 0, 0), datetime.datetime(2004, 1, 20, 0, 0), 'Shipped', None, 177),
 (10211, datetime.datetime(2004, 1, 15, 0, 0), datetime.datetime(2004, 1, 25, 0, 0), datetime.datetime(2004, 1, 18, 0, 0), 'Shipped', None, 406),
 (10212, datetime.datetime(2004, 1, 16, 0, 0), datetime.datetime(2004, 1, 24, 0, 0), datetime.datetime(2004, 1, 18, 0, 0), 'Shipped', None, 141),
 (10213, datetime.datetime(2004, 1, 22, 0, 0), datetime.datetime(2004, 1, 28, 0, 0), datetime.datetime(2004, 1, 27, 0, 0), 'Shipped', 'Difficult to negotiate with customer. We need more marketing materials', 489),
 (10214, datetime.datetime(2004, 1, 26, 0, 0), datetime.datetime(2004, 2, 4, 0, 0), datetime.datetime(2004, 1, 29, 0, 0), 'Shipped', None, 458),
 (10215, datetime.datetime(2004, 1, 29, 0, 0), datetime.datetime(2004, 2, 8, 0, 0), datetime.datetime(2004, 2, 1, 0, 0), 'Shipped', 'Customer requested that FedEx Ground is used for this shipping', 475),
 (10216, datetime.datetime(2004, 2, 2, 0, 0), datetime.datetime(2004, 2, 10, 0, 0), datetime.datetime(2004, 2, 4, 0, 0), 'Shipped', None, 256),
 (10217, datetime.datetime(2004, 2, 4, 0, 0), datetime.datetime(2004, 2, 14, 0, 0), datetime.datetime(2004, 2, 6, 0, 0), 'Shipped', None, 166),
 (10218, datetime.datetime(2004, 2, 9, 0, 0), datetime.datetime(2004, 2, 16, 0, 0), datetime.datetime(2004, 2, 11, 0, 0), 'Shipped', 'Customer requested that ad materials (such as posters, pamphlets) be included in the shippment', 473),
 (10219, datetime.datetime(2004, 2, 10, 0, 0), datetime.datetime(2004, 2, 17, 0, 0), datetime.datetime(2004, 2, 12, 0, 0), 'Shipped', None, 487),
 (10220, datetime.datetime(2004, 2, 12, 0, 0), datetime.datetime(2004, 2, 19, 0, 0), datetime.datetime(2004, 2, 16, 0, 0), 'Shipped', None, 189),
 (10221, datetime.datetime(2004, 2, 18, 0, 0), datetime.datetime(2004, 2, 26, 0, 0), datetime.datetime(2004, 2, 19, 0, 0), 'Shipped', None, 314),
 (10222, datetime.datetime(2004, 2, 19, 0, 0), datetime.datetime(2004, 2, 27, 0, 0), datetime.datetime(2004, 2, 20, 0, 0), 'Shipped', None, 239),
 (10223, datetime.datetime(2004, 2, 20, 0, 0), datetime.datetime(2004, 2, 29, 0, 0), datetime.datetime(2004, 2, 24, 0, 0), 'Shipped', None, 114),
 (10224, datetime.datetime(2004, 2, 21, 0, 0), datetime.datetime(2004, 3, 2, 0, 0), datetime.datetime(2004, 2, 26, 0, 0), 'Shipped', 'Customer has worked with some of our vendors in the past and is aware of their MSRP', 171),
 (10225, datetime.datetime(2004, 2, 22, 0, 0), datetime.datetime(2004, 3, 1, 0, 0), datetime.datetime(2004, 2, 24, 0, 0), 'Shipped', None, 298),
 (10226, datetime.datetime(2004, 2, 26, 0, 0), datetime.datetime(2004, 3, 6, 0, 0), datetime.datetime(2004, 3, 2, 0, 0), 'Shipped', None, 239),
 (10227, datetime.datetime(2004, 3, 2, 0, 0), datetime.datetime(2004, 3, 12, 0, 0), datetime.datetime(2004, 3, 8, 0, 0), 'Shipped', None, 146),
 (10228, datetime.datetime(2004, 3, 10, 0, 0), datetime.datetime(2004, 3, 18, 0, 0), datetime.datetime(2004, 3, 13, 0, 0), 'Shipped', None, 173),
 (10229, datetime.datetime(2004, 3, 11, 0, 0), datetime.datetime(2004, 3, 20, 0, 0), datetime.datetime(2004, 3, 12, 0, 0), 'Shipped', None, 124),
 (10230, datetime.datetime(2004, 3, 15, 0, 0), datetime.datetime(2004, 3, 24, 0, 0), datetime.datetime(2004, 3, 20, 0, 0), 'Shipped', 'Customer very concerned about the exact color of the models. There is high risk 

14. Lista los clientes y sus pagos totales, ordenados de mayor a menor.

In [44]:
%%sql
SELECT p."customerNumber", SUM(p."amount") AS total_pagos
   FROM payments p
   GROUP BY p."customerNumber"
   ORDER BY total_pagos DESC;

 * postgresql://postgres:***@localhost/classicmodels
98 rows affected.


[(141, 715738.9800000001),
 (124, 584188.2400000001),
 (114, 180585.06999999998),
 (151, 177913.95),
 (148, 156251.03),
 (323, 154622.08000000002),
 (187, 148410.09),
 (276, 137034.22),
 (321, 132340.78),
 (146, 130305.35),
 (278, 127529.69),
 (353, 126983.19),
 (119, 116949.68000000001),
 (363, 116449.29000000001),
 (496, 114497.19),
 (458, 112440.09),
 (298, 108777.92),
 (131, 107639.94),
 (145, 107446.5),
 (398, 105548.73),
 (166, 105420.56999999999),
 (161, 104545.22),
 (121, 104224.79),
 (334, 103896.73999999999),
 (320, 101872.51999999999),
 (157, 98509.25),
 (167, 97562.47),
 (311, 95706.15),
 (186, 95546.46),
 (175, 95424.63),
 (205, 93803.29999999999),
 (282, 91655.61),
 (286, 90545.37),
 (386, 90143.31),
 (227, 89909.79999999999),
 (259, 89223.14),
 (462, 88627.49),
 (385, 87468.3),
 (172, 86553.52),
 (406, 86436.97),
 (382, 85060.0),
 (249, 82223.23),
 (324, 80556.73),
 (239, 80375.24),
 (112, 80180.98),
 (319, 78432.16),
 (486, 77726.59),
 (448, 76776.44),
 (128, 75937.76000000001),
 (209, 75859.32),
 (379, 73533.65),
 (181, 72497.64),
 (240, 71783.75),
 (350, 71547.53),
 (455, 70378.65),
 (202, 70122.19),
 (424, 69214.33),
 (299, 69059.04),
 (233, 68977.67),
 (216, 68520.47),
 (250, 67659.19),
 (260, 66812.0),
 (129, 66710.56),
 (412, 66704.94),
 (495, 65541.74),
 (177, 62361.219999999994),
 (314, 62253.850000000006),
 (171, 61781.7),
 (201, 61167.18000000001),
 (242, 60483.36),
 (450, 59551.38),
 (256, 58876.409999999996),
 (339, 57939.34),
 (357, 56662.38),
 (204, 55577.26),
 (333, 55190.16),
 (452, 51059.990000000005),
 (484, 50987.850000000006),
 (447, 49967.78),
 (189, 49898.270000000004),
 (344, 46751.14),
 (211, 45480.79),
 (471, 44920.759999999995),
 (475, 43748.72),
 (144, 43680.65),
 (487, 42570.37),
 (347, 41506.19),
 (328, 38281.509999999995),
 (362, 33533.47),
 (173, 32198.690000000002),
 (415, 31310.09),
 (489, 29586.15),
 (456, 29230.43),
 (381, 29217.18),
 (473, 25358.32),
 (103, 22314.36),
 (198, 21554.260000000002),
 (219, 7918.6)]

15. Muestra los empleados que no reportan a ningún gerente (es decir, cuyo campo reportsTo es NULL).

In [45]:
%%sql
SELECT * FROM employees e
   WHERE e."reportsTo" IS NULL;

 * postgresql://postgres:***@localhost/classicmodels
1 rows affected.


[(1002, 'Murphy', 'Diane', 'x5800', 'dmurphy@classicmodelcars.com', '1', None, 'President')]

16. Encuentra los clientes que no han realizado ningún pedido.

In [46]:
%%sql
SELECT * FROM customers c
WHERE c."customerNumber" NOT IN (SELECT o."customerNumber" FROM orders o);

 * postgresql://postgres:***@localhost/classicmodels
24 rows affected.


[(125, 'Havel & Zbyszek Co', 'Piestrzeniewicz', 'Zbyszek ', '(26) 642-7555', 'ul. Filtrowa 68', None, 'Warszawa', None, '01-012', 'Poland', None, 0.0),
 (168, 'American Souvenirs Inc', 'Franco', 'Keith', '2035557845', '149 Spinnaker Dr.', 'Suite 101', 'New Haven', 'CT', '97823', 'USA', 1286.0, 0.0),
 (169, 'Porto Imports Co.', 'de Castro', 'Isabel ', '(1) 356-5555', 'Estrada da saúde n. 58', None, 'Lisboa', None, '1756', 'Portugal', None, 0.0),
 (206, 'Asian Shopping Network, Co', 'Walker', 'Brydey', '+612 9411 1555', 'Suntec Tower Three', '8 Temasek', 'Singapore', None, '038988', 'Singapore', None, 0.0),
 (223, 'Natürlich Autos', 'Kloss', 'Horst ', '0372-555188', 'Taucherstraße 10', None, 'Cunewalde', None, '01307', 'Germany', None, 0.0),
 (237, 'ANG Resellers', 'Camino', 'Alejandra ', '(91) 745 6555', 'Gran Vía, 1', None, 'Madrid', None, '28001', 'Spain', None, 0.0),
 (247, 'Messner Shopping Network', 'Messner', 'Renate ', '069-0555984', 'Magazinweg 7', None, 'Frankfurt', None, '60528', 'Germany', None, 0.0),
 (273, 'Franken Gifts, Co', 'Franken', 'Peter ', '089-0877555', 'Berliner Platz 43', None, 'München', None, '80805', 'Germany', None, 0.0),
 (293, 'BG&E Collectables', 'Harrison', 'Ed', '+41 26 425 50 01', 'Rte des Arsenaux 41 ', None, 'Fribourg', None, '1700', 'Switzerland', None, 0.0),
 (303, 'Schuyler Imports', 'Schuyler', 'Bradley', '+31 20 491 9555', 'Kingsfordweg 151', None, 'Amsterdam', None, '1043 GR', 'Netherlands', None, 0.0),
 (307, 'Der Hund Imports', 'Andersen', 'Mel', '030-0074555', 'Obere Str. 57', None, 'Berlin', None, '12209', 'Germany', None, 0.0),
 (335, 'Cramer Spezialitäten, Ltd', 'Cramer', 'Philip ', '0555-09555', 'Maubelstr. 90', None, 'Brandenburg', None, '14776', 'Germany', None, 0.0),
 (348, 'Asian Treasures, Inc.', 'McKenna', 'Patricia ', '2967 555', '8 Johnstown Road', None, 'Cork', 'Co. Cork', None, 'Ireland', None, 0.0),
 (356, 'SAR Distributors, Co', 'Kuger', 'Armand', '+27 21 550 3555', '1250 Pretorius Street', None, 'Hatfield', 'Pretoria', '0028', 'South Africa', None, 0.0),
 (361, 'Kommission Auto', 'Josephs', 'Karin', '0251-555259', 'Luisenstr. 48', None, 'Münster', None, '44087', 'Germany', None, 0.0),
 (369, 'Lisboa Souveniers, Inc', 'Rodriguez', 'Lino ', '(1) 354-2555', 'Jardim das rosas n. 32', None, 'Lisboa', None, '1675', 'Portugal', None, 0.0),
 (376, 'Precious Collectables', 'Urs', 'Braun', '0452-076555', 'Hauptstr. 29', None, 'Bern', None, '3012', 'Switzerland', 1702.0, 0.0),
 (409, 'Stuttgart Collectable Exchange', 'Müller', 'Rita ', '0711-555361', 'Adenauerallee 900', None, 'Stuttgart', None, '70563', 'Germany', None, 0.0),
 (443, 'Feuer Online Stores, Inc', 'Feuer', 'Alexander ', '0342-555176', 'Heerstr. 22', None, 'Leipzig', None, '04179', 'Germany', None, 0.0),
 (459, 'Warburg Exchange', 'Ottlieb', 'Sven ', '0241-039123', 'Walserweg 21', None, 'Aachen', None, '52066', 'Germany', None, 0.0),
 (465, 'Anton Designs, Ltd.', 'Anton', 'Carmen', '+34 913 728555', 'c/ Gobelas, 19-1 Urb. La Florida', None, 'Madrid', None, '28023', 'Spain', None, 0.0),
 (477, 'Mit Vergnügen & Co.', 'Moos', 'Hanna ', '0621-08555', 'Forsterstr. 57', None, 'Mannheim', None, '68306', 'Germany', None, 0.0),
 (480, 'Kremlin Collectables, Co.', 'Semenov', 'Alexander ', '+7 812 293 0521', '2 Pobedy Square', None, 'Saint Petersburg', None, '196143', 'Russia', None, 0.0),
 (481, 'Raanan Stores, Inc', 'Altagar,G M', 'Raanan', '+ 972 9 959 8555', '3 Hagalim Blv.', None, 'Herzlia', None, '47625', 'Israel', None, 0.0)]

17. Muestra los productos que nunca han sido vendidos en ningún pedido.

In [47]:
%%sql
SELECT * FROM products p
WHERE p."productCode" NOT IN (SELECT o."productCode" FROM orderdetails o);

 * postgresql://postgres:***@localhost/classicmodels
1 rows affected.


[('S18_3233', '1985 Toyota Supra', 'Classic Cars', '1:18', 'Highway 66 Mini Classics', 'This model features soft rubber tires, working steering, rubber mud guards, authentic Ford logos, detailed undercarriage, opening doors and hood, removable split rear gate, full size spare mounted in bed, detailed interior with opening glove box', 7733, 57.01, 107.57)]

18. Calcula el precio de compra promedio de todos los productos.

In [48]:
%%sql
SELECT AVG(p."buyPrice") AS precio_promedio FROM products p;

 * postgresql://postgres:***@localhost/classicmodels
1 rows affected.


[(54.395181818181825,)]

19. Lista los clientes y el número de pedidos que han realizado.

In [49]:
%%sql
SELECT o."customerNumber", COUNT(o."orderNumber") AS numero_pedidos
FROM orders o
GROUP BY o."customerNumber";

 * postgresql://postgres:***@localhost/classicmodels
98 rows affected.


[(209, 3),
 (347, 2),
 (455, 2),
 (181, 3),
 (321, 4),
 (205, 3),
 (448, 3),
 (146, 3),
 (201, 3),
 (350, 3),
 (333, 3),
 (382, 4),
 (314, 3),
 (386, 3),
 (216, 3),
 (278, 3),
 (450, 4),
 (406, 3),
 (424, 3),
 (484, 2),
 (233, 3),
 (334, 3),
 (144, 4),
 (462, 3),
 (299, 2),
 (276, 4),
 (471, 3),
 (473, 2),
 (219, 2),
 (175, 3),
 (363, 3),
 (362, 3),
 (379, 3),
 (323, 5),
 (320, 3),
 (114, 5),
 (415, 1),
 (167, 3),
 (112, 3),
 (475, 2),
 (487, 2),
 (458, 3),
 (124, 17),
 (452, 3),
 (227, 2),
 (128, 4),
 (282, 4),
 (173, 2),
 (339, 2),
 (166, 4),
 (311, 3),
 (103, 3),
 (344, 2),
 (385, 3),
 (189, 2),
 (239, 2),
 (161, 4),
 (121, 4),
 (119, 4),
 (286, 2),
 (240, 2),
 (328, 3),
 (157, 4),
 (202, 2),
 (260, 2),
 (381, 4),
 (412, 3),
 (447, 3),
 (187, 3),
 (298, 2),
 (259, 2),
 (495, 2),
 (172, 3),
 (141, 26),
 (186, 3),
 (250, 3),
 (211, 2),
 (131, 4),
 (198, 3),
 (324, 3),
 (256, 2),
 (177, 2),
 (357, 3),
 (242, 3),
 (319, 2),
 (204, 2),
 (249, 2),
 (398, 4),
 (171, 2),
 (353, 5),
 (456, 2),
 (489, 2),
 (145, 5),
 (148, 5),
 (129, 3),
 (496, 4),
 (486, 3),
 (151, 4)]

20. Encuentra el total de ventas por año.

In [75]:
%%sql
SELECT EXTRACT(YEAR FROM o."orderDate") AS order_year,
       SUM(od."quantityOrdered" * od."priceEach") AS total_sales
FROM orders o
JOIN orderdetails od ON o."orderNumber" = od."orderNumber"
GROUP BY order_year
ORDER BY order_year;



 * postgresql://postgres:***@localhost/classicmodels
3 rows affected.


[(Decimal('2003'), 3317348.389999999),
 (Decimal('2004'), 4515905.510000002),
 (Decimal('2005'), 1770936.7099999993)]

21. Muestra los detalles de las órdenes combinados con la información del producto para cada artículo.

In [60]:
%%sql
SELECT o."orderNumber", o."orderDate", od."productCode", p."productName", od."quantityOrdered", od."priceEach"
FROM orders o
JOIN orderdetails od ON o."orderNumber" = od."orderNumber"
JOIN products p ON od."productCode" = p."productCode";

 * postgresql://postgres:***@localhost/classicmodels
2996 rows affected.


[(10100, datetime.datetime(2003, 1, 6, 0, 0), 'S18_1749', '1917 Grand Touring Sedan', 30, 136.0),
 (10100, datetime.datetime(2003, 1, 6, 0, 0), 'S18_2248', '1911 Ford Town Car', 50, 55.09),
 (10100, datetime.datetime(2003, 1, 6, 0, 0), 'S18_4409', '1932 Alfa Romeo 8C2300 Spider Sport', 22, 75.46),
 (10100, datetime.datetime(2003, 1, 6, 0, 0), 'S24_3969', '1936 Mercedes Benz 500k Roadster', 49, 35.29),
 (10101, datetime.datetime(2003, 1, 9, 0, 0), 'S18_2325', '1932 Model A Ford J-Coupe', 25, 108.06),
 (10101, datetime.datetime(2003, 1, 9, 0, 0), 'S18_2795', '1928 Mercedes-Benz SSK', 26, 167.06),
 (10101, datetime.datetime(2003, 1, 9, 0, 0), 'S24_1937', '1939 Chevrolet Deluxe Coupe', 45, 32.53),
 (10101, datetime.datetime(2003, 1, 9, 0, 0), 'S24_2022', '1938 Cadillac V-16 Presidential Limousine', 46, 44.35),
 (10102, datetime.datetime(2003, 1, 10, 0, 0), 'S18_1342', '1937 Lincoln Berline', 39, 95.55),
 (10102, datetime.datetime(2003, 1, 10, 0, 0), 'S18_1367', '1936 Mercedes-Benz 500K Special Roadster', 41, 43.13),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S10_1949', '1952 Alpine Renault 1300', 26, 214.3),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S10_4962', '1962 LanciaA Delta 16V', 42, 119.67),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S12_1666', '1958 Setra Bus', 27, 121.64),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S18_1097', '1940 Ford Pickup Truck', 35, 94.5),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S18_2432', '1926 Ford Fire Engine', 22, 58.34),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S18_2949', '1913 Ford Model T Speedster', 27, 92.19),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S18_2957', '1934 Ford V8 Coupe', 35, 61.84),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S18_3136', '18th Century Vintage Horse Carriage', 25, 86.92),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S18_3320', '1917 Maxwell Touring Car', 46, 86.31),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S18_4600', '1940s Ford truck', 36, 98.07),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S18_4668', '1939 Cadillac Limousine', 41, 40.75),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S24_2300', '1962 Volkswagen Microbus', 36, 107.34),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S24_4258', '1936 Chrysler Airflow', 25, 88.62),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S32_1268', '1980’s GM Manhattan Express', 31, 92.46),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S32_3522', '1996 Peterbilt 379 Stake Bed with Outrigger', 45, 63.35),
 (10103, datetime.datetime(2003, 1, 29, 0, 0), 'S700_2824', '1982 Camaro Z28', 42, 94.07),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S12_3148', '1969 Corvair Monza', 34, 131.44),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S12_4473', '1957 Chevy Pickup', 41, 111.39),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S18_2238', '1998 Chrysler Plymouth Prowler', 24, 135.9),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S18_2319', '1964 Mercedes Tour Bus', 29, 122.73),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S18_3232', '1992 Ferrari 360 Spider red', 23, 165.95),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S18_4027', '1970 Triumph Spitfire', 38, 119.2),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S24_1444', '1970 Dodge Coronet', 35, 52.02),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S24_2840', '1958 Chevy Corvette Limited Edition', 44, 30.41),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S24_4048', '1992 Porsche Cayenne Turbo Silver', 26, 106.45),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S32_2509', '1954 Greyhound Scenicruiser', 35, 51.95),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S32_3207', "1950's Chicago Surface Lines Streetcar", 49, 56.55),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S50_1392', 'Diamond T620 Semi-Skirted Tanker', 33, 114.59),
 (10104, datetime.datetime(2003, 1, 31, 0, 0), 'S50_1514', '1962 City of Detroit Streetcar', 32, 53.31),
 (10105, datetime.datetime(2003, 2, 11, 0, 0), 'S10_4757', '1972

22. Encuentra los empleados que trabajan en oficinas ubicadas en los Estados Unidos.

In [61]:
%%sql
SELECT e.* FROM employees e
JOIN offices o ON e."officeCode" = o."officeCode"
WHERE o."country" = 'USA';

 * postgresql://postgres:***@localhost/classicmodels
10 rows affected.


[(1002, 'Murphy', 'Diane', 'x5800', 'dmurphy@classicmodelcars.com', '1', None, 'President'),
 (1056, 'Patterson', 'Mary', 'x4611', 'mpatterso@classicmodelcars.com', '1', 1002.0, 'VP Sales'),
 (1076, 'Firrelli', 'Jeff', 'x9273', 'jfirrelli@classicmodelcars.com', '1', 1002.0, 'VP Marketing'),
 (1143, 'Bow', 'Anthony', 'x5428', 'abow@classicmodelcars.com', '1', 1056.0, 'Sales Manager (NA)'),
 (1165, 'Jennings', 'Leslie', 'x3291', 'ljennings@classicmodelcars.com', '1', 1143.0, 'Sales Rep'),
 (1166, 'Thompson', 'Leslie', 'x4065', 'lthompson@classicmodelcars.com', '1', 1143.0, 'Sales Rep'),
 (1188, 'Firrelli', 'Julie', 'x2173', 'jfirrelli@classicmodelcars.com', '2', 1143.0, 'Sales Rep'),
 (1216, 'Patterson', 'Steve', 'x4334', 'spatterson@classicmodelcars.com', '2', 1143.0, 'Sales Rep'),
 (1286, 'Tseng', 'Foon Yue', 'x2248', 'ftseng@classicmodelcars.com', '3', 1143.0, 'Sales Rep'),
 (1323, 'Vanauf', 'George', 'x4102', 'gvanauf@classicmodelcars.com', '3', 1143.0, 'Sales Rep')]

23. Lista los clientes junto con el nombre de su representante de ventas.

In [62]:
%%sql
SELECT c."customerName", e."firstName", e."lastName"
FROM customers c
JOIN employees e ON c."salesRepEmployeeNumber" = e."employeeNumber";

 * postgresql://postgres:***@localhost/classicmodels
100 rows affected.


[('Signal Collectibles Ltd.', 'Leslie', 'Jennings'),
 ('The Sharp Gifts Warehouse', 'Leslie', 'Jennings'),
 ('Corporate Gift Ideas Co.', 'Leslie', 'Jennings'),
 ('Technics Stores Inc.', 'Leslie', 'Jennings'),
 ('Mini Wheels Co.', 'Leslie', 'Jennings'),
 ('Mini Gifts Distributors Ltd.', 'Leslie', 'Jennings'),
 ('West Coast Collectables Co.', 'Leslie', 'Thompson'),
 ("Men 'R' US Retailers, Ltd.", 'Leslie', 'Thompson'),
 ('Collectable Mini Designs Co.', 'Leslie', 'Thompson'),
 ('Boards & Toys Co.', 'Leslie', 'Thompson'),
 ('Toys4GrownUps.com', 'Leslie', 'Thompson'),
 ('Signal Gift Stores', 'Leslie', 'Thompson'),
 ('Diecast Collectables', 'Julie', 'Firrelli'),
 ('Collectables For Less Inc.', 'Julie', 'Firrelli'),
 ('Classic Gift Ideas, Inc', 'Julie', 'Firrelli'),
 ('Mini Creations Ltd.', 'Julie', 'Firrelli'),
 ('Online Mini Collectables', 'Julie', 'Firrelli'),
 ('Cambridge Collectables Co.', 'Julie', 'Firrelli'),
 ('FunGiftIdeas.com', 'Steve', 'Patterson'),
 ('Online Diecast Creations Co.', 'Steve', 'Patterson'),
 ('Gifts4AllAges.com', 'Steve', 'Patterson'),
 ("Marta's Replicas Co.", 'Steve', 'Patterson'),
 ('Auto-Moto Classics Inc.', 'Steve', 'Patterson'),
 ('Diecast Classics Inc.', 'Steve', 'Patterson'),
 ('Microscale Inc.', 'Foon Yue', 'Tseng'),
 ('Super Scale Inc.', 'Foon Yue', 'Tseng'),
 ('Classic Legends Inc.', 'Foon Yue', 'Tseng'),
 ('Québec Home Shopping Network', 'Foon Yue', 'Tseng'),
 ('Vitachrome Inc.', 'Foon Yue', 'Tseng'),
 ('American Souvenirs Inc', 'Foon Yue', 'Tseng'),
 ('Muscle Machine Inc', 'Foon Yue', 'Tseng'),
 ('Motor Mint Distributors Inc.', 'George', 'Vanauf'),
 ('Gift Ideas Corp.', 'George', 'Vanauf'),
 ('Tekni Collectables Inc.', 'George', 'Vanauf'),
 ('Mini Classics', 'George', 'Vanauf'),
 ('Royal Canadian Collectables, Ltd.', 'George', 'Vanauf'),
 ('Canadian Gift Exchange Network', 'George', 'Vanauf'),
 ('Gift Depot Inc.', 'George', 'Vanauf'),
 ('Land of Toys Inc.', 'George', 'Vanauf'),
 ('Auto Canal+ Petit', 'Loui', 'Bondur'),
 ('Reims Collectables', 'Loui', 'Bondur'),
 ('Marseille Mini Autos', 'Loui', 'Bondur'),
 ('Lyon Souveniers', 'Loui', 'Bondur'),
 ("La Corne D'abondance, Co.", 'Loui', 'Bondur'),
 ('Saveley & Henriot, Co.', 'Loui', 'Bondur'),
 ('Auto Associés & Cie.', 'Gerard', 'Hernandez'),
 ('Alpha Cognac', 'Gerard', 'Hernandez'),
 ('Mini Caravy', 'Gerard', 'Hernandez'),
 ('Daedalus Designs Imports', 'Gerard', 'Hernandez'),
 ('Euro+ Shopping Channel', 'Gerard', 'Hernandez'),
 ('La Rochelle Gifts', 'Gerard', 'Hernandez'),
 ('Atelier graphique', 'Gerard', 'Hernandez'),
 ('Frau da Collezione', 'Pamela', 'Castillo'),
 ('Mini Auto Werke', 'Pamela', 'Castillo'),
 ("L'ordine Souveniers", 'Pamela', 'Castillo'),
 ('Salzburg Collectables', 'Pamela', 'Castillo'),
 ('Royale Belge', 'Pamela', 'Castillo'),
 ('Petit Auto', 'Pamela', 'Castillo'),
 ('Rovelli Gifts', 'Pamela', 'Castillo'),
 ('Amica Models & Co.', 'Pamela', 'Castillo'),
 ('Heintze Collectables', 'Pamela', 'Castillo'),
 ('Danish Wholesale Imports', 'Pamela', 'Castillo'),
 ('Double Decker Gift Stores, Ltd', 'Larry', 'Bott'),
 ('Suominen Souveniers', 'Larry', 'Bott'),
 ('Stylish Desk Decors, Co.', 'Larry', 'Bott'),
 ('Oulu Toy Supplies, Inc.', 'Larry', 'Bott'),
 ('giftsbymail.co.uk', 'Larry', 'Bott'),
 ('UK Collectables, Ltd.', 'Larry', 'Bott'),
 ('AV Stores, Co.', 'Larry', 'Bott'),
 ('Toys of Finland, Co.', 'Larry', 'Bott'),
 ('Scandinavian Gift Ideas', 'Barry', 'Jones'),
 ('Bavarian Collectables Imports, Co.', 'Barry', 'Jones'),
 ('Norway Gifts By Mail, Co.', 'Barry', 'Jones'),
 ('Toms Spezialitäten, Ltd', 'Barry', 'Jones'),
 ('Clover Collections, Co.', 'Barry', 'Jones'),
 ('Herkku Gifts', 'Barry', 'Jones'),
 ('Volvo Model Replicas, Co', 'Barry', 'Jones'),
 ('Blauer See Auto, Co.', 'Barry', 'Jones'),
 ('Baane Mini Imports', 'Barry', 'Jones'),
 ('Australian Collectables, Ltd', 'Andy', 'Fixter'),
 ('Australian Gift Network, Co', 'Andy', 'Fixter'),
 ('Souveniers And Things Co.', 'Andy', 'Fixter'),
 ("Anna's Decorations, Ltd", 'Andy', 'Fixter'),
 ('Aust

24. Calcula el total de pagos recibidos en cada ciudad.

In [79]:
%%sql
SELECT o."city", SUM(p."amount") AS total_pagos
FROM payments p
INNER JOIN customers c ON p."customerNumber" = c."customerNumber"
INNER JOIN offices o ON c."salesRepEmployeeNumber"::text = o."officeCode"
GROUP BY o."city";

 * postgresql://postgres:***@localhost/classicmodels
0 rows affected.


[]

25. Muestra los productos que tienen menos de 100 unidades en stock (quantityInStock).

In [66]:
%%sql
SELECT * FROM products WHERE "quantityInStock" < 100;

 * postgresql://postgres:***@localhost/classicmodels
2 rows affected.


[('S12_1099', '1968 Ford Mustang', 'Classic Cars', '1:12', 'Autoart Studio Design', 'Hood, doors and trunk all open to reveal highly detailed interior features. Steering wheel actually turns the front wheels. Color dark green.', 68, 95.34, 194.57),
 ('S24_2000', '1960 BSA Gold Star DBD34', 'Motorcycles', '1:24', 'Highway 66 Mini Classics', 'Detailed scale replica with working suspension and constructed from over 70 parts', 15, 37.32, 76.17)]

26. Encuentra los clientes que han realizado pedidos con un monto total superior a $10,000.

In [80]:
%%sql
SELECT c."customerNumber", c."customerName", SUM(od."quantityOrdered" * od."priceEach") AS monto_total
FROM customers c
JOIN orders o ON c."customerNumber" = o."customerNumber"
JOIN orderdetails od ON o."orderNumber" = od."orderNumber"
GROUP BY c."customerNumber", c."customerName"
HAVING SUM(od."quantityOrdered" * od."priceEach") > 10000;


 * postgresql://postgres:***@localhost/classicmodels
97 rows affected.


[(475, 'West Coast Collectables Co.', 43748.719999999994),
 (379, 'Collectables For Less Inc.', 73533.65000000001),
 (350, 'Marseille Mini Autos', 71547.53),
 (339, 'Classic Gift Ideas, Inc', 57939.340000000004),
 (452, 'Mini Auto Werke', 51059.99),
 (129, 'Mini Wheels Co.', 66710.56),
 (175, 'Gift Depot Inc.', 95424.63),
 (344, 'CAF Imports', 46751.14000000001),
 (216, 'Enaco Distributors', 68520.47),
 (385, 'Cruz & Sons Co.', 87468.29999999999),
 (124, 'Mini Gifts Distributors Ltd.', 591827.3399999996),
 (242, 'Alpha Cognac', 60483.359999999986),
 (119, 'La Rochelle Gifts', 158573.11999999997),
 (189, 'Clover Collections, Co.', 49898.270000000004),
 (398, 'Tokyo Collectables, Ltd', 105548.73000000001),
 (260, 'Royal Canadian Collectables, Ltd.', 66812.0),
 (363, 'Online Diecast Creations Co.', 116449.29000000001),
 (186, 'Toys of Finland, Co.', 95546.46),
 (167, 'Herkku Gifts', 97562.46999999999),
 (347, "Men 'R' US Retailers, Ltd.", 41506.189999999995),
 (323, 'Down Under Souveniers, Inc', 154622.08000000005),
 (240, 'giftsbymail.co.uk', 71783.75),
 (334, 'Suominen Souveniers', 103896.73999999999),
 (462, 'FunGiftIdeas.com', 88627.48999999999),
 (282, 'Souveniers And Things Co.', 133907.12),
 (256, 'Auto Associés & Cie.', 58876.409999999996),
 (447, 'Gift Ideas Corp.', 49967.77999999999),
 (455, 'Super Scale Inc.', 70378.65000000001),
 (181, 'Vitachrome Inc.', 72497.64),
 (321, 'Corporate Gift Ideas Co.', 132340.77999999997),
 (456, 'Microscale Inc.', 29230.43),
 (328, 'Tekni Collectables Inc.', 81806.55),
 (314, 'Petit Auto', 70851.58),
 (353, 'Reims Collectables', 126983.18999999997),
 (121, 'Baane Mini Imports', 104224.78999999996),
 (471, 'Australian Collectables, Ltd', 55866.02),
 (166, 'Handji Gifts& Co', 107746.75),
 (424, 'Classic Legends Inc.', 69214.33000000002),
 (177, 'Osaka Souveniers Co.', 62361.219999999994),
 (458, 'Corrida Auto Replicas, Ltd', 112440.08999999998),
 (103, 'Atelier graphique', 22314.36),
 (249, 'Amica Models & Co.', 82223.23),
 (211, 'King Kong Collectables, Co.', 45480.78999999999),
 (202, 'Canadian Gift Exchange Network', 70122.18999999999),
 (128, 'Blauer See Auto, Co.', 75937.76),
 (131, 'Land of Toys Inc.', 149085.14999999997),
 (311, 'Oulu Toy Supplies, Inc.', 95706.15),
 (145, 'Danish Wholesale Imports', 129085.12000000002),
 (259, 'Toms Spezialitäten, Ltd', 89223.14000000003),
 (157, 'Diecast Classics Inc.', 104358.69),
 (406, 'Auto Canal+ Petit', 86436.96999999999),
 (489, 'Double Decker Gift Stores, Ltd', 29586.149999999998),
 (450, 'The Sharp Gifts Warehouse', 143536.27000000002),
 (486, 'Motor Mint Distributors Inc.', 77726.59000000001),
 (233, 'Québec Home Shopping Network', 68977.67),
 (112, 'Signal Gift Stores', 80180.97999999998),
 (239, 'Collectable Mini Designs Co.', 80375.23999999999),
 (320, 'Mini Creations Ltd.', 101872.52),
 (298, 'Vida Sport, Ltd', 108777.92),
 (148, 'Dragon Souveniers, Ltd.', 156251.03),
 (357, 'GiftsForHim.com', 94431.76000000001),
 (412, 'Extreme Desk Decorations, Ltd', 90332.37999999996),
 (381, 'Royale Belge', 29217.18),
 (144, 'Volvo Model Replicas, Co', 66694.81999999999),
 (205, 'Toys4GrownUps.com', 93803.29999999999),
 (114, 'Australian Collectors, Co.', 180585.07),
 (187, 'AV Stores, Co.', 148410.09000000003),
 (173, 'Cambridge Collectables Co.', 32198.69),
 (415, 'Bavarian Collectables Imports, Co.', 31310.089999999997),
 (141, 'Euro+ Shopping Channel', 820689.5399999992),
 (286, "Marta's Replicas Co.", 90545.37),
 (172, "La Corne D'abondance, Co.", 86553.52),
 (362, 'Gifts4AllAges.com', 84340.32),
 (319, 'Mini Classics', 78432.16000000002),
 (151, 'Muscle Machine Inc', 177913.95000000007),
 (487, 'Signal Collectibles Ltd.', 42570.37),
 (278, 'Rovelli Gifts', 127529.68999999999),
 (204, 'Online Mini Collectables', 55577.26000000001),
 (473, 'Frau da Collezione', 25358.32),
 (324, 'Stylish Desk Decors, Co.', 80556.73000000001),
 (201, 'UK Collectables, Ltd.', 106610.71999999999),
 (171, 'Daedalus Designs Imports', 61781.7),
 (386, "L'ordine So

27. Lista los empleados y el número de clientes que atienden.

In [81]:
%%sql
SELECT e."employeeNumber", e."firstName", e."lastName", COUNT(c."customerNumber") AS numero_clientes
FROM employees e
LEFT JOIN customers c ON e."employeeNumber" = c."salesRepEmployeeNumber"
GROUP BY e."employeeNumber", e."firstName", e."lastName";


 * postgresql://postgres:***@localhost/classicmodels
23 rows affected.


[(1504, 'Barry', 'Jones', 9),
 (1612, 'Peter', 'Marsh', 5),
 (1188, 'Julie', 'Firrelli', 6),
 (1619, 'Tom', 'King', 0),
 (1337, 'Loui', 'Bondur', 6),
 (1088, 'William', 'Patterson', 0),
 (1501, 'Larry', 'Bott', 8),
 (1165, 'Leslie', 'Jennings', 6),
 (1621, 'Mami', 'Nishi', 5),
 (1286, 'Foon Yue', 'Tseng', 7),
 (1056, 'Mary', 'Patterson', 0),
 (1166, 'Leslie', 'Thompson', 6),
 (1625, 'Yoshimi', 'Kato', 0),
 (1216, 'Steve', 'Patterson', 6),
 (1076, 'Jeff', 'Firrelli', 0),
 (1370, 'Gerard', 'Hernandez', 7),
 (1702, 'Martin', 'Gerard', 6),
 (1143, 'Anthony', 'Bow', 0),
 (1323, 'George', 'Vanauf', 8),
 (1102, 'Gerard', 'Bondur', 0),
 (1401, 'Pamela', 'Castillo', 10),
 (1611, 'Andy', 'Fixter', 5),
 (1002, 'Diane', 'Murphy', 0)]

28. Calcula el importe total de los pedidos que están en proceso (estado 'In Process').

In [69]:
%%sql
SELECT SUM(od."quantityOrdered" * od."priceEach") AS total_importe_en_proceso
FROM orders o
JOIN orderdetails od ON o."orderNumber" = od."orderNumber"
WHERE o."status" = 'In Process';

 * postgresql://postgres:***@localhost/classicmodels
1 rows affected.


[(135271.52,)]

29. Encuentra los productos que han sido pedidos más de 100 veces en total.

In [82]:
%%sql
SELECT "productCode", SUM("quantityOrdered") AS total_cantidad_pedida
FROM orderdetails
GROUP BY "productCode"
HAVING SUM("quantityOrdered") > 100;

 * postgresql://postgres:***@localhost/classicmodels
109 rows affected.


[('S32_2206', Decimal('906')),
 ('S700_2466', Decimal('984')),
 ('S700_3505', Decimal('952')),
 ('S700_2824', Decimal('997')),
 ('S18_2949', Decimal('1038')),
 ('S50_4713', Decimal('992')),
 ('S12_3380', Decimal('925')),
 ('S24_4278', Decimal('1009')),
 ('S10_2016', Decimal('999')),
 ('S18_2325', Decimal('957')),
 ('S18_1889', Decimal('972')),
 ('S18_2795', Decimal('880')),
 ('S18_4933', Decimal('767')),
 ('S10_1678', Decimal('1057')),
 ('S24_3420', Decimal('884')),
 ('S24_2766', Decimal('949')),
 ('S18_3320', Decimal('992')),
 ('S18_3140', Decimal('883')),
 ('S24_2840', Decimal('983')),
 ('S24_2300', Decimal('1029')),
 ('S18_4600', Decimal('1061')),
 ('S24_2360', Decimal('947')),
 ('S18_4027', Decimal('945')),
 ('S18_1984', Decimal('917')),
 ('S12_1666', Decimal('972')),
 ('S24_1628', Decimal('915')),
 ('S24_2000', Decimal('1015')),
 ('S700_4002', Decimal('1085')),
 ('S18_1589', Decimal('914')),
 ('S24_3856', Decimal('1052')),
 ('S18_1097', Decimal('999')),
 ('S12_4473', Decimal('1056')),
 ('S18_1342', Decimal('1111')),
 ('S18_1749', Decimal('918')),
 ('S18_2625', Decimal('945')),
 ('S700_2610', Decimal('1020')),
 ('S32_1268', Decimal('911')),
 ('S72_1253', Decimal('960')),
 ('S700_3167', Decimal('1047')),
 ('S24_3432', Decimal('894')),
 ('S12_2823', Decimal('1028')),
 ('S18_3259', Decimal('918')),
 ('S24_3191', Decimal('870')),
 ('S24_1937', Decimal('937')),
 ('S700_1691', Decimal('894')),
 ('S24_3151', Decimal('991')),
 ('S50_1514', Decimal('966')),
 ('S32_4485', Decimal('898')),
 ('S18_3029', Decimal('966')),
 ('S700_1138', Decimal('934')),
 ('S24_3969', Decimal('824')),
 ('S18_3482', Decimal('915')),
 ('S24_1578', Decimal('1033')),
 ('S18_2581', Decimal('917')),
 ('S32_1374', Decimal('1014')),
 ('S18_2248', Decimal('832')),
 ('S24_2887', Decimal('873')),
 ('S18_1129', Decimal('947')),
 ('S700_2834', Decimal('973')),
 ('S50_1392', Decimal('979')),
 ('S18_2319', Decimal('1053')),
 ('S24_1785', Decimal('972')),
 ('S24_2011', Decimal('1011')),
 ('S72_3212', Decimal('958')),
 ('S32_3207', Decimal('934')),
 ('S10_4757', Decimal('1030')),
 ('S24_4048', Decimal('867')),
 ('S24_3816', Decimal('923')),
 ('S18_2957', Decimal('985')),
 ('S700_1938', Decimal('898')),
 ('S24_4258', Decimal('983')),
 ('S32_2509', Decimal('955')),
 ('S18_3136', Decimal('907')),
 ('S18_4409', Decimal('866')),
 ('S18_3232', Decimal('1808')),
 ('S18_3685', Decimal('948')),
 ('S18_2870', Decimal('855')),
 ('S700_2047', Decimal('897')),
 ('S18_4522', Decimal('990')),
 ('S24_1046', Decimal('803')),
 ('S18_2238', Decimal('986')),
 ('S10_4698', Decimal('985')),
 ('S32_3522', Decimal('988')),
 ('S18_3782', Decimal('959')),
 ('S18_1662', Decimal('1040')),
 ('S24_2972', Decimal('912')),
 ('S24_2841', Decimal('940')),
 ('S24_3949', Decimal('1051')),
 ('S12_1099', Decimal('933')),
 ('S18_3856', Decimal('1076')),
 ('S24_2022', Decimal('955')),
 ('S18_4721', Decimal('1013')),
 ('S700_3962', Decimal('896')),
 ('S24_3371', Decimal('969')),
 ('S12_4675', Decimal('992')),
 ('S18_1367', Decimal('960')),
 ('S10_4962', Decimal('932')),
 ('S50_1341', Decimal('1074')),
 ('S10_1949', Decimal('961')),
 ('S24_4620', Decimal('941')),
 ('S24_1444', Decimal('976')),
 ('S12_3990', Decimal('900')),
 ('S32_4289', Decimal('972')),
 ('S18_4668', Decimal('995')),
 ('S18_2432', Decimal('998')),
 ('S12_3148', Decimal('963')),
 ('S12_1108', Decimal('1019')),
 ('S12_3891', Decimal('965')),
 ('S18_3278', Decimal('974'))]

30. Muestra las líneas de productos y el número de productos que pertenecen a cada línea.

In [71]:
%%sql
SELECT "productLine", COUNT("productCode") AS numero_productos
FROM products
GROUP BY "productLine";

 * postgresql://postgres:***@localhost/classicmodels
7 rows affected.


[('Classic Cars', 38),
 ('Trains', 3),
 ('Planes', 12),
 ('Trucks and Buses', 11),
 ('Vintage Cars', 24),
 ('Motorcycles', 13),
 ('Ships', 9)]